### ISSUE TITLE
Chyba předávání šablony

### ISSUE THREAD

**Issue by Cuchulain** [obrejla/Eciovni#11]
Při implementaci příkladu z http://addons.nette.org/ondrej-brejla/eciovni mi hází chybu:

Recoverable Error

Argument 1 passed to OndrejBrejla\Eciovni\Eciovni::generate() must be an instance of Nette\Application\UI\ITemplate, instance of Nette\Templating\FileTemplate given, called in C:\rds\xampp\htdocs\projekty\weby\ambernode.cz\libs\OndrejBrejla\Eciovni\Eciovni.php on line 59

Čím to může být? Verze mi připadají v pohodě.

moje konfigurace:
PHP 5.6.3, Nette Framework 2.0.4 (released on 2012-07-30), mpdf v5.7.1

Popis chyby - http://ambernode.cz/_podklady/Recoverable%20Error.htm

**Comment by Cuchulain** [comment]
Když jsem v deklaraci třídy Eciovni v parametrech metod nahradil odkazy na \Nette\Templating\ITemplate za \Nette\Templating\ITemplate, tak už to šlape.

**Comment by janbarasek** [comment]
Ahoj, upravil jsem implementaci třídy `Eciovni` tak, aby třídu `ITemplate` vůbec nepotřebovala a instanci Latte si vytváří uvnitř interně sama.

Renderovací mechanismus obsahuje výchozí Latte šablonu, případě lze kdykoli předat nová cesta setterem `setTemplatePath(string $templatePath): void`.

Ideální je pak definice i přímo v NEONu pro DIC:

```yaml
service:
   eciovni:
      factory: OndrejBrejla\Eciovni\Eciovni
      setup:
         - setTemplatePath(%appDir%/model/my-template.latte)
```
